CREATE TABLE IF NOT EXISTS public.reminder_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id bigint NOT NULL,
  is_active boolean NULL,
  message character varying NULL,
  type character varying NULL,
  CONSTRAINT reminder_messages_pkey PRIMARY KEY (id),
  CONSTRAINT reminder_messages_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id)
);
